# Generated by Django 4.2.8 on 2024-01-12 04:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('content', models.TextField(unique=True)),
            ],
        ),
    ]
